FRONT-END-BOOTCAMP-PLUS-3/moongchija

app/page.tsx
=> Develop -> Main Test

components/input-filed/InputField.module.scss
<br />
- input radius 10px로 수정
<br />
👋🏻
=> [style] InputField CSS 수정 (radius)

app/page.tsx, components/input-plus-button/InputPlusButton.module.scss, components/input-plus-button/InputPlusButton.tsx
- <br />
- 플러스 버튼 공통컴포넌트입니다.
사용법
```jsx
import React from "react";
import InputPlusButton from "./components/InputPlusButton"; // 경로를 실제 컴포넌트 위치에 맞게 수정
const App: React.FC = () => {
const handleButtonClick = () => {
alert("Button clicked!");
};
return (
<div style={{ display: "flex", flexDirection: "column", alignItems: "center", marginTop: "50px" }}>
<h1>Input Plus Button Example</h1>
<InputPlusButton onClick={handleButtonClick} />
</div>
);
};
export default App;
```
<br />
👋🏻
=> [style ] input plus button 컴포넌트 생성

components/header/ArrowHeader.tsx, components/header/DropdownMenu.module.scss, components/header/DropdownMenu.tsx, components/header/Header.module.scss, components/header/Header.tsx, components/header/IconHeader.tsx
- <br />
- 헤더 컴포넌트 추가
- layout에 설정할 예정이므로 사용 방법 없습니다!
<br />
- 추후 로그인 기능 완료 되면 헤더에 지금 로그인 되어 있는 유저 정보 렌더링이랑 로그아웃 기능 추가하겠습니다~
=> [style] Header 컴포넌트 추가

app/page.module.css, app/page.module.scss, app/page.tsx
- <br />
- 초기화면 페이지 구성 및 로그인 버튼 클릭시 로그인 페이지 이동
-
<br />
👋🏻
=> [style] UI작업 초기화면 페이지 작업

components/header/DropdownMenu.tsx, components/header/IconHeader.tsx
<br />
- logo 파일 svg로 수정
- link 경로 수정
<br />
=> [fix] header 이미지 경로 및 link 수정

app/globals.css, components/input-filed/InputField.module.scss, components/input-filed/InputFiled.tsx
<br />
- placeholder props 추가
- global에 input { box-sizing: border-box; } 추가
<br />
=> [style] input field 수정

app/globals.css
<br />
- * { box-sizing: border-box; } 수정
- css 정리
<br />
-
-
=> [style] globals.css 수정

components/input-filed/InputField.module.scss, components/input-filed/InputFiled.tsx
<br />
- 스타일 수정
- 유효성 검사 실패 시 디자인 변경 기능 추가
- 기능 사용 방법1 : submit 버튼 클릭 시 유효성 검사
```js
"use client"
import InputField from "@/components/input-filed/InputFiled";
import { useState } from "react";
const ListPage = () => {
const [inputValue, setInputValue] = useState("");
const [error, setError] = useState("");
const handleValidation = () => {
// 유효성 검사 로직
if (inputValue.trim() === "") {
setError("내용을 작성해주세요.");
return false;
} else if (inputValue.length < 3) {
setError("최소 3글자 이상 작성해주세요.");
return false;
} else {
setError(""); // 유효성 검사 통과
return true;
}
};
const handleSubmit = (e: React.FormEvent) => {
e.preventDefault(); // 기본 제출 동작 방지
if (handleValidation()) {
alert("성공!!");
}
};
return (
<form onSubmit={handleSubmit}>
<InputField
label="이름"
value={inputValue}
onChange={(e) => …
```
=> [style] (01.23 최신) InputField 오류 메세지 기능 추가 및 스타일 수정

components/button/Button.module.scss
<br />
- 기존 button height -> padding 으로 변경
-
<br />
-
-
=> [style] Button 공통 컴포넌트 height -> padding 으로 수정

app/login/_components/LogoWithTitle.module.scss, app/login/_components/LogoWithTitle.tsx, app/signup/_components/AuthForm.module.scss, app/signup/_components/AuthForm.tsx, app/signup/_hooks/useInput.ts, app/signup/page.tsx, app/signup/signup.module.scss
<br />
- AuthForm 컴포넌트에서 사용하는 useInput 훅 작업
- signup 페이지 UI 작업 완료
<br />
-
-
=> [style] signup 페이지 UI 작업

components/circleButton/CircleButton.module.scss, components/circleButton/CircleButton.tsx
<br />
- 오른쪽 하단에 동그라미 + 버튼 컴포넌트 추가 했습니다
<br />
- 사용 방법 : 부모 컴포넌트는 꼭 **position: relative**로 하셔야 합니다!!!
```js
"use client";
import CircleButton from "@/components/circleButton/CircleButton";
import React from "react";
const ParentComponent = () => {
const handleClick = () => {
console.log("Circle button clicked!");
};
return (
<div style={{ position: "relative", height: "100vh", backgroundColor: "#f0f0f0" }}>
<h1>Parent Component</h1>
<CircleButton onClick={handleClick} />
</div>
);
};
export default ParentComponent;
```
<br />
-
-
=> [style] circle button 컴포넌트 생성

app/(with-arrow-header)/vote/[id]/_components/PlaceVote.module.scss, app/(with-arrow-header)/vote/[id]/_components/PlaceVote.tsx, app/(with-arrow-header)/vote/[id]/page.tsx
<br />
- 선택된 장소를 state로 관리하고 선택될때마다 state변경
-
<br />
-
-
=> [style] PlaceVote 컴포넌트 제작

app/signup/_components/AuthForm.tsx, app/signup/_hooks/useInput.ts, app/signup/_hooks/useValidate.ts, components/input-filed/InputField.module.scss, components/input-filed/InputFiled.tsx
<br />
- validate - 
- 이메일 : 이메일 형식
- 닉네임 : 소문자, 한글, 숫자 포함 10자리 이하
- 비밀번호 : 소문자, 숫자 8자리 이상
<br />
-
-
=> [style] 회원가입 페이지 유효성 검사 규칙 및 UI 작업

app/(with-arrow-header)/vote/[id]/_components/PlaceVote.module.scss, app/(with-arrow-header)/vote/[id]/_components/PlaceVote.tsx, app/(with-arrow-header)/vote/[id]/_components/TimeVote.module.scss, app/(with-arrow-header)/vote/[id]/_components/TimeVote.tsx, app/(with-arrow-header)/vote/[id]/page.tsx, app/globals.css
<br />
- 페이지 변환
state함수를 사용하여 상태에따라 화면에 보이는 컴포넌트가 달라지도록 구현하였다.
사용되는 컴포넌트에 props로 페이지 상태를 변환해주는 set함수를 전달 해주어 사용하였다.
<br />
-
-
=> [style] vote url 내에서 컴포넌트 변환 및 스타일 수정

app/(with-icon-header)/mypage/_components/AppointmentCount.module.scss, app/(with-icon-header)/mypage/_components/AppointmentCount.tsx, app/(with-icon-header)/mypage/_components/Calendar.module.scss, app/(with-icon-header)/mypage/_components/Calendar.tsx, app/(with-icon-header)/mypage/mypage.module.scss, app/(with-icon-header)/mypage/page.tsx, app/signup/_components/AuthForm.tsx
<br />
- 마이페이지 기본 UI 작업 일단 PR하기
-
<br />
-
-
=> [style] UI/my page 작업

app/(with-arrow-header)/vote-result/[id]/_components/TimeResult.module.scss, app/(with-arrow-header)/vote-result/[id]/_components/TimeResult.tsx, app/(with-arrow-header)/vote-result/[id]/page.tsx, app/(with-arrow-header)/vote-result/[id]/voteResult.module.scss
<br />
- 투표결과 페이지 스타일작업
<br />
-
-
=> [style] vote-result-timeVote 스타일 추가

app/user/appointments/[id]/vote-result/components/TimeResult.module.scss, app/user/appointments/[id]/vote-result/components/TimeResult.tsx, app/user/appointments/[id]/vote-result/layout.tsx, app/user/appointments/[id]/vote-result/page.tsx, app/user/appointments/[id]/vote-result/voteResult.module.scss
<br />
- vote-result 페이지에서 시간투표 컴포넌트 작업완료
- vote-result 페이지는 시간/장소 투표결과 페이지를 나누지 않고 한번에 만들 예정
<br />
=> [style] vote-result 페이지 시간투표결과 컴포넌트 ui작성

app/user/mypage.module.scss, app/user/page.tsx
<br />
- 마이페이지 탈퇴하기 버튼 마크업 및 스타일링
- 헤더 부분 및 달력은 제외 추가 예정
<br />
-
-
=> [style] 마이페이지 UI 수정 및 달력 제외 완성

app/user/components/DeleteAccountModalContent.module.scss, app/user/components/DeleteAccountModalContent.tsx, app/user/components/UserAppointmentCount.module.scss, app/user/components/UserAppointmentCount.tsx, app/user/components/UserImage.module.scss, app/user/components/UserImage.tsx, app/user/components/UserInfo.module.scss, app/user/components/UserInfo.tsx, app/user/components/UserName.module.scss, app/user/components/UserName.tsx, app/user/components/UserProfile.module.scss, app/user/components/UserProfile.tsx, app/user/page.tsx
<br />
- 마이페이지 유저 프로필 부분을 따로 컴포넌트로 분리하여 작업했습니다.
-
<br />
-
-
=> [reafactor] 마이페이지 컴포넌트 구조 리팩토링

app/user/components/Calendar.module.scss, app/user/components/Calendar.tsx, app/user/components/MyCalendar.scss, app/user/components/MyCalendar.tsx, app/user/page.tsx, package-lock.json, package.json
<br />
- FullCalendar라이브러리를 사용하여 마이페이지 달력 추가
- FullCalendar사용이유 나중에 기능 추가를 위해 드래그앤드롭 기능도 있고, react-calendar보다 더 많은 기능을 지원해주고,
- react-big-calendar를 사용하려 했으나 react 18버전까지 지원하여 FullCalendar를 선택했습니다.
-
<br />
- 고려사항 : 달력에 1월 2월만 표시하려고하였는데, 연도를 붙이는게 좋을 것 같아 일단 추가된 상태로 PR날립니다.
-
=> Feat/my page/calendar

app/user/components/UserImage.tsx, app/user/components/UserImageModalContent.module.scss, app/user/components/UserImageModalContent.tsx
<br />
- 유저 이모지 수정 버튼 클릭 시 나오는 모달 기능 추가하였습니다.
-
<br />
-
-
=> [feat] 마이페이지 Emoji 수정 모달 추가

app/(anon)/login/login.module.scss, app/(anon)/login/page.tsx, app/(anon)/signup/components/AuthForm.module.scss, app/(anon)/signup/components/AuthForm.tsx
<br />
- 로그인 하러가기 링크 추가 이유
- 잘못 들어왔을 시 로그인하러 가기로 갈 버튼이 없어서 추가했습니다.
- 
<br />
-
-
=> [refactor] 회원가입 페이지 하단 로그인 하러가기 링크 추가

components/input-filed/InputField.module.scss
<br />
- input-field 너비 100%로 변경
<br />
- 로그인, 회원가입 페이지에서 이상 없어서 푸쉬 합니다!
- 문제 생길 시 width: 100%;만 지우면 됩니다
=> [style] input-field 너비 100%로 변경

app/(anon)/signup/components/AuthForm.tsx, app/(anon)/signup/hooks/useForm.ts, app/api/auth/signup/route.ts, application/usecases/auth/SignUpUseCase.ts, domain/entities/User.ts, domain/repositories/UserEmojiRepository.ts, domain/repositories/UserRepository.ts, infrastructure/repositories/SbUserEmojiRepository.ts, infrastructure/repositories/SbUserRepository.ts
<br />
- 회원가입 기능 추가 
- 회원가입 성공 시 `/app/appointment` 경로로 이동합니다.
- 회원가입 시 랜덤으로 이모지 추가하여 supabase table에 저장합니다.
- 회원가입 버튼 클릭 시 처리 중... 상태 추가 
- 회원가입 시 중복 이메일 체크합니다. 중복일 시 메시지 출력  (이미 사용중인 이메일 입니다.)
<br />
-
-
=> [feat] 회원가입 기능 추가

app/(anon)/signup/components/AuthForm.tsx
<br />
- 이메일 중복 오류 메시지를 이메일 input 하단으로 변경하였습니다.
-
<br />
-
-
=> [feat] 이메일 중복 오류 메시지 표시 추가

app/(anon)/login/components/LoginForm.tsx, app/api/auth/login/route.ts, app/api/auth/logout/route.ts, app/api/auth/signup/route.ts, app/user/page.tsx, application/usecases/auth/LoginUsecase.ts, application/usecases/auth/LogoutUsecase.ts, application/usecases/auth/SignUpUseCase.ts, domain/entities/Auth.ts, domain/repositories/AuthRepository.ts, infrastructure/repositories/SbAuthRepository.ts
<br />
- 로그인 기능 및 로그아웃 기능 추가하였습니다.
- 로그인 완료 하면 `user/appointments` 로 리디렉션 하였고 로컬스토리지에 토큰 값 넣었습니다.
- 로그아웃 버튼이 헤더가 아직 없어서 일단 임시로 마이페이지 하단에 넣어서 진행하였습니다.
- 로그아웃 완료 시 초기화면으로 리디렉션 및 로컬 스토리지 토큰 삭제하였습니다.
<br />
-
-
=> [feat] 로그인 및 로그아웃 기능 추가

app/user/appointments/page.tsx
<br />
- `module.scss` 불러오는 코드에서 오타가 발생하여 수정했습니다.
-
<br />
-
-
=> [fix] Appointments.module.scss 오타 수정 a -> A

app/user/appointments/[id]/ confirm/page.tsx, app/user/appointments/[id]/confirm/confirm.module.scss, app/user/appointments/[id]/confirm/layout.tsx, app/user/appointments/[id]/confirm/page.tsx, app/user/appointments/[id]/vote-result/page.tsx
<br />
- 약속 만들기-시간 페이지를 참조하여 기간을 선택하는 달력 구현
- 장소선택하는 select를 추가로 만듦
- 약속 확정하기 버튼을 누르면 자신이 선택한 일자, 시간, 장소를 다시한번 확인시켜주는 모달창 추가
<br />
-
-
=> [style] 약속확정페이지 디자인추가

app/user/appointments/[id]/confirm/complete/complete.module.scss, app/user/appointments/[id]/confirm/complete/page.tsx, app/user/appointments/[id]/confirm/page.tsx
<br />
- `useParams()`를 통해 id값을 가져옴
```tsx
const params = useParams(); // URL에서 ID 추출
const appointmentId = params.id as string;
```
- `setTimeout()` 함수를 이용해서 초대링크 복사후 복사확인메세지가 2초후 사라지게 만듦
<br />
-
-
=> [style] 약속확정완료 페이지 스타일 추가

app/(anon)/login/components/KakaoLogin.module.scss, app/(anon)/login/components/KakaoLogin.tsx, app/(anon)/login/login.module.scss, app/(anon)/login/page.tsx
<br />
- 로그인 페이지에서 카카오 로그인 컴포넌트 분리하였습니다.
-
<br />
-
-
=> [refactor] 카카오 로그인 컴포넌트 분리

app/user/appointments/create/place/page.tsx, app/user/appointments/create/place/place.module.scss, app/user/appointments/page.tsx
<br />
- create place 화면 기능 및 디자인 완료했습니다
<br />
- 현재 UI는 input text 필드를 추가할 수만 있고 삭제는 불가여서 삭제 기능도 추가했습니다
=> [style] UI/create/place

app/user/appointments/create/complete/complete.module.scss, app/user/appointments/create/complete/page.tsx, app/user/appointments/create/place/page.tsx
<br />
- create complete 페이지 완료
<br />
=> [style] create complete 페이지 완료

app/user/appointments/[id]/entry/entry.module.scss, app/user/appointments/[id]/entry/page.tsx, app/user/appointments/create/complete/page.tsx
<br />
- 방 참여하기 페이지 디자인 및 기능 추가
<br />
=> [style] 방 참여 페이지 완료

app/(anon)/signup/components/AuthForm.tsx, app/api/auth/signup/route.ts, app/globals.css, application/usecases/auth/SignUpUseCase.ts, infrastructure/repositories/SbUserRepository.ts
- [] 디자인 작업
<br />
- 회원가입 완료 후 토큰이 저장되지 않습니다. 그래서 회원가입 완료 후 로그인 기능까지 추가하여 토큰을 받아와서 로컬 스토리지에 저장했습니다.
-
<br />
-
-
=> [fix] 회원가입 완료 후 자동으로 로그인 

app/user/appointments/[id]/vote-result/components/PlaceResult.module.scss, app/user/appointments/[id]/vote-result/components/TimeResult.module.scss, app/user/appointments/[id]/vote-result/voteResult.module.scss
<br />
- 투표 결과 페이지 버튼 fix 삭제, 시간/장소 컴포넌트 높이 맞춤
<br />
-
-
=> [style] 투표 결과 페이지 버튼 fix 삭제, 시간/장소 컴포넌트 높이 맞춤

components/tabMenu/TabMenu.module.scss
<br />
- 탭 메뉴 컴포넌트 높이 패딩 값으로 변경
<br />
=> [style] 탭 메뉴 컴포넌트 높이 패딩 값으로 변경

app/user/appointments/Appointments.module.scss, app/user/appointments/components/AppointmentCard.module.scss, app/user/appointments/components/AppointmentCard.tsx, app/user/appointments/page.tsx, components/tabMenu/TabMenu.module.scss, utils/dateUtils/dateUtils.ts
<br />
- 약속 리스트 페이지 카드 디자인 수정
- 유틸 함수 분리
<br />
=> [style] UI/appointments

domain/entities/Appointment.ts, domain/repositories/AppointmentRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts
=> [feat] SbAppointmentRepository.ts 약속테이블 관련 레포지토리 작성

domain/entities/PlaceVote.ts, domain/entities/PlaceVoteUser.ts, domain/entities/TimeVote.ts, domain/entities/TimeVoteUser.ts, domain/repositories/PlaceVoteRepository.ts, domain/repositories/PlaceVoteUserRepository.ts, domain/repositories/TimeVoteRepository.ts, domain/repositories/TimeVoteUserRepository.ts, infrastructure/repositories/SbPlaceVoteRepository.ts, infrastructure/repositories/SbPlaceVoteUserRepository.ts, infrastructure/repositories/SbTimeVoteRepository.ts, infrastructure/repositories/SbTimeVoteUserRepository.ts
<br />
- infrastructure/reposotories에 레포지토리 파일을 추가 하기위해
domain/entitis와 domain/repositories에서 타입을 지정
- 투표 기능과 관련된 timeVote, timeVoteUser, placeVote, placeVoteUser 의 repository를 추가
<br />
-
-
=> [feat] 투표기능 관련 repository 추가

app/api/user/appointments/[id]/time-vote/route.ts, app/layout.tsx, app/user/appointments/[id]/vote-time/page.tsx, application/usecases/appointment/DfGetAppointmentTimeUsecase.ts.ts, application/usecases/appointment/dto/AppointmentTimeDto.ts, context/TimeVoteContext.tsx, domain/repositories/AppointmentRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts
<br />
1.  약속id로 투표시간 범위 불러오기 기능
- repository에 id 값으로 start_time, end_time 불러오는 코드 추가
```tsx
import { createClient } from "@/utils/supabase/server";
import { AppointmentRepository } from "@/domain/repositories/AppointmentRepository";
import { Appointment } from "@/domain/entities/Appointment";
export class SbAppointmentRepository implements AppointmentRepository {
async getAppointmentTime(appointmentId: number): Promise<Appointment | null> {
const supabase = await createClient();
const { data, error } = await supabase
.from("appointment")
.select("id, start_time, end_time")
.eq("id", appointmentId)
.single();
if (error) {
console.error("Error fetching appointment time:", error.message);
return null;
}
return data ? { id: data.id, start_time: data.start_time, end_time: data.end_time } : …
```
=> [feat] 시간투표페이지에서 특정약속의 투표시간범위 불러오기, 선택한시간 context로 저장하기 기능 추가

app/api/user/appointments/[id]/place-vote/route.ts, app/api/user/appointments/[id]/vote/route.ts, app/user/appointments/[id]/vote-place/page.tsx, application/usecases/appointment/DfGetPlaceVotesUsecase.ts, application/usecases/appointment/DfSubmitVoteUsecase.ts, application/usecases/appointment/dto/PlaceVoteDto.ts, application/usecases/appointment/dto/VoteDto.ts, domain/repositories/TimeVoteRepository.ts, infrastructure/repositories/SbTimeVoteRepository.ts, package-lock.json, package.json, utils/supabase/client.ts, utils/supabase/cookieHelper.ts
<br />
- 약속id로 장소 리스트를 불러오는 usecase 추가
- 장소투표 후 context에 저장된 시간 투표결과와 함계 서버에 post하는 usecase작성했으나 user_id 를 가져오는 과정에서 오류가 발생...
<br />
-
-
=> [feat] 장소투표 리스트 get구현, 투표제출기능 구현 중

app/user/appointments/[id]/confirm/complete/complete.module.scss, app/user/appointments/[id]/confirm/complete/page.tsx, app/user/appointments/[id]/confirm/confirm.module.scss, app/user/appointments/[id]/confirm/page.tsx, app/user/appointments/[id]/vote-place/votePlace.module.scss, app/user/appointments/[id]/vote-result/page.tsx, app/user/appointments/[id]/vote-result/voteResult.module.scss, app/user/appointments/[id]/vote-time/page.tsx, app/user/appointments/[id]/vote-time/voteTime.module.scss, components/button/Button.module.scss
<br />
- lg 버튼의 크기 조정
- 기존 : `width: 380px;`
- 변경 : `max-width: 400px;   width: 100%;`
<br />
-
-
=> [style] button 컴포넌트 디자인 수정

app/api/auth/callback/route.ts, app/api/auth/login/route.ts
<br />
- 자체 로그인 및 카카오 로그인 후 토큰을 쿠키에 저장하였습니다.
- access_token 유효 시간을 1시간으로 설정했습니다.
-
<br />
-
-
=> [feat] 로그인 후 토큰저장 방식 변경

app/user/page.tsx
<br />
- 마이페이지에서 사용하는 아이콘 헤더 컴포넌트 추가하였습니다.
-
<br />
-
-
=> [style] 마이 페이지 아이콘 헤더 추가

app/(anon)/login/components/LoginForm.tsx
<br />
- 기존 로컬 스토리지에 저장되는 토큰을 제거 하였습니다.
-
<br />
-
-
=> [fix] 로컬 스토리지 저장 제거

app/user/appointments/Appointments.module.scss, app/user/appointments/page.tsx
<br />
- 약속 리스트 페이지 스크롤, 검색 수정
<br />
=> [style] 약속 리스트 페이지 스크롤, 검색 수정

infrastructure/repositories/SbAuthRepository.ts
<br />
- supabase에서 사용자가 있다면 로그인 없다면 회원가입을 진행합니다. 진행 후 사용자 정보를 업데이트 하는 과정에서 로그아웃 후 로그인을 다시할때 또 업데이트되는 오류가 발생하여 닉네임과 이모지 값이 null일 경우에만 업데이트 하도록 변경하였습니다.
-
<br />
-
-
=> [fix] 카카오 로그아웃 후 다시 로그인 시 중복 업데이트 되는 현상 해결

app/user/appointments/components/AppointmentCard.module.scss, app/user/appointments/components/AppointmentCard.tsx, app/user/appointments/page.tsx, components/header/DropdownMenu.tsx, components/header/IconHeader.tsx, utils/dateUtils/dateUtils.ts
<br />
- 헤더 링크 수정
- 날짜 유틸 함수 계산 수정
<br />
=> [style] 헤더 링크 수정 및 데이터 유틸 함수 수정

app/api/auth/callback/route.ts, app/api/auth/login/route.ts, app/api/auth/logout/route.ts, package-lock.json, package.json
<br />
- 기존 access_token을 그대로 쿠키에 저장했습니다. 하지만 필요한 정보인 userId만 쿠키에 저장하기로 변경했습니다.
-
<br />
-
-
=> [feat] 로그인 시 토큰 저장 값 수정

app/api/auth/token/route.ts, app/api/user/appointments/[id]/vote/route.ts, app/user/appointments/[id]/vote-place/page.tsx, application/usecases/appointment/DfSubmitVoteUsecase.ts, domain/repositories/PlaceVoteUserRepository.ts, domain/repositories/TimeVoteRepository.ts, infrastructure/repositories/SbPlaceVoteUserRepository.ts, infrastructure/repositories/SbTimeVoteRepository.ts, package-lock.json, package.json, utils/supabase/client.ts, utils/supabase/cookie.ts
<br />
투표 내용 저장 로직
1. 시간페이지에서 start_time, end_time으로 타임테이블 생성
2. 선택된시간 context로 저장
3. 약속id로 장소투표리스트불러옴
4. 장소 선택
5. context에 저장된 시간목록과 함꼐 투표내용 api로 전달
6. 장소는 장소id로 place_vote_user테이블에 추가
7. 시간은 시간을 바탕으로 time_vote테이블에 시간내용이 있으면 추가 후 time_vote_user테이블에도 추가
8. time_vote테이블에 투표한 시간이 없다면 time_vote테이블에 시간정보 추가 후 time_vote_user테이블에 정보 추가
<br />
-
-
=> [feat] 투표내용 저장기능 추가

app/user/mypage.module.scss, app/user/page.tsx, components/header/Header.module.scss, components/header/Header.tsx, components/header/IconHeader.tsx
<br />
- 기존 닉네임이 나오는 헤더부분을 props 변경을 통해 마이페이지에서 로그아웃 버튼이 나오게 변경하였습니다.
- 기존 로그아웃 버튼 제거 후 헤더 로그아웃 버튼으로 변경하였습니다.
-
<br />
-
-
=> [refactor] 마이 페이지 헤더 부분 수정 및 로그아웃 버튼 수정

app/api/auth/callback/route.ts, app/api/auth/login/route.ts
<br />
- 로그인 후 Supabase 자동 생성 토큰 삭제 추가하였습니다.
-
<br />
-
-
=> [feat]  로그인 후 Supabase 자동 생성 토큰 삭제 추가

app/api/auth/logout/route.ts, domain/repositories/AuthRepository.ts, infrastructure/repositories/SbAuthRepository.ts
<br />
- supabase에서 지원하는 signOut 함수 사용하지 않고 그냥 route.ts에서 쿠키를 삭제하고 홈 화면으로 이동시켰습니다.
-
<br />
-
-
=> [refactor] supabase 함수 사용하지 않고 구현하기

app/api/user/appointments/[id]/vote-result/route.ts, app/user/appointments/[id]/vote-result/components/TimeResult.tsx, app/user/appointments/[id]/vote-result/page.tsx, application/usecases/vote/DfGetVoteResultUsecase.ts, domain/entities/Member.ts, domain/repositories/AppointmentRepository.ts, domain/repositories/PlaceVoteUserRepository.ts, domain/repositories/TimeVoteUserRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts, infrastructure/repositories/SbMemberRepository.ts, infrastructure/repositories/SbPlaceVoteUserRepository.ts, infrastructure/repositories/SbTimeVoteUserRepository.ts, utils/dateUtils/dateUtils.ts
<br />
1. 해당 약속의 모든 멤버 조회 (nickname 포함)
```tsx   
const members = await this.appointmentRepo.getMembersByAppointment(
appointmentId
);
```
2. 해당 약속의 시간 투표 결과 조회
```tsx
const timeVotes = await this.timeVoteRepo.getTimeVotesByAppointment(
appointmentId
);
```
3. 각 시간별 투표자 조회 (nickname 포함)
```tsx
const timeResults = await Promise.all(
timeVotes.map(async (timeVote) => {
const users = await this.timeVoteUserRepo.getUsersByTime(timeVote.id);
return {
date: timeVote.time,
user: users.map((user) => user.nickname), // ✅ nickname 반환
};
})
);
```
4. 해당 약속의 장소 투표 결과 조회
```tsx
const placeVotes = await this.placeVoteRepo.getPlacesByAppointment(
appointmentId
);
```
5. 각 장소별 투표자 조회 (nickname 포함)
```tsx
const placeResults = await Promise.all(
placeVotes.map(async (placeVote) => {
const users = await …
```
=> [feat] 시간/장소 투표결과 불러오는 DfGetVoteResultUsecase.ts 작성

app/api/user/appointments/[id]/confirm/route.ts, app/user/appointments/[id]/confirm/complete/page.tsx, app/user/appointments/[id]/confirm/page.tsx, application/usecases/appointment/DfConfirmUseCase.ts, domain/repositories/AppointmentRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts
<br />
- 장소투표에서 만들었던 DfGetPlaceVoteUsecase 재사용 해서 장소리스트를 불러옴
- 방장이 최종선택한 날짜,시간,장소를 appointment테이블에 등록하고 약속상태를 confirmed로 바꾸는 DfConfirmAppointmentUseCase 추가
- 페이지에서 날짜, 시간을 따로 저장 했지만 api로 보낼때 두 정보를 합쳐서 api로 보냄
<br />
-
-
=> [feat] 약속확정 기능 추가

app/api/user/appointments/[id]/place-vote/route.ts, app/user/appointments/[id]/vote-place/page.tsx, app/user/appointments/[id]/vote-result/page.tsx, app/user/appointments/[id]/vote-time/page.tsx, application/usecases/vote/dto/PlaceVoteDto.ts
<br />
- 장소투표adapter수정
- 시간투표페이지 사용하지 않는 변수 제거
- PlaceVoteDto에 장소 id추가
- api 확인용 console.log 제거
<br />
-
-
=> [feat] 장소투표adapter수정, 시간투표페이지 사용하지 않는 변수 제거, PlaceVoteDto에 장소 id추가

app/(anon)/login/components/KakaoLogin.tsx, app/(anon)/login/components/KakaoSDKLoader.tsx, app/api/auth/callback/route.ts, app/api/auth/kakao-user/route.ts, application/usecases/auth/DfSignUpUseCase.ts, application/usecases/auth/DfSocialLoginUseCase.ts, application/usecases/auth/dto/SocialLoginResponseDto.ts, domain/entities/User.ts, domain/repositories/AuthRepository.ts, domain/repositories/UserRepository.ts, global.d.ts, infrastructure/repositories/SbAuthRepository.ts, infrastructure/repositories/SbUserRepository.ts
<br />
- 기존 supabase signInWithOAuth 사용하여 구현을 하였으나, 직접 구현하는거로 수정하였습니다.
- 나중에 supabase가 바뀌더라도 해당 함수 로그인, 회원가입을 조금만 수정하면 됩니다.
- 클라이언트 카카오 로그인 버튼 클릭 SDK 활용 -> 카카오 로그인 후 -> 카카오에서 인가 코드를 붙여서 callback -> 인가 코드를 카카오 API에 전달하여 사용자 access_token을 받아오기 -> access_token을 카카오 API에 전달하여 사용자 정보 받아오기 -> 사용자 kakao_id로 테이블에 사용자가 있는지 확인 없다면 테이블에 추가, 있다면 로그인 -> 토큰 쿠키에 저장 및 페이지 이동
- 입니다.
<br />
-
-
=> [feat] kakao login

app/api/auth/login/route.ts, domain/repositories/AuthRepository.ts, infrastructure/repositories/SbAuthRepository.ts
<br />
- 로그인 실패 시 사용자가 없을 때 에러메시지를 변경하였습니다.
-
<br />
-
-
=> [feat] 로그인 시 에러메시지 변경

app/user/appointments/[id]/confirm/page.tsx, app/user/appointments/[id]/vote-place/page.tsx, app/user/appointments/[id]/vote-result/page.tsx, app/user/appointments/[id]/vote-time/page.tsx
<br />
- 공통 컴포넌트에 추가 된 로딩 스피너 투표관련페이지에 추가
<br />
-
-
=> [style] loading spinner 추가

app/(anon)/login/components/LogoWithTitle.tsx, app/(anon)/page.tsx, app/user/appointments/[id]/confirm/complete/complete.module.scss, app/user/appointments/[id]/confirm/complete/page.tsx, app/user/appointments/create/complete/page.tsx, components/moongchi/Moongchi.module.scss, components/moongchi/Moongchi.tsx, package-lock.json, package.json
<br />
1. 움직이는 로고 구현
- Framer Motion을 사용해서 애니메이션이 있는 로고 컴포넌트를 구현
2. 로고 쓰는 페이지에서 로고이미지 대신 로고 컴포넌트로 대체
<br />
-
-
=> [style] 움직이는 로고 제작

app/api/user/appointments/create/route.ts, app/api/user/appointments/route.ts, app/user/appointments/create/components/complete.tsx, app/user/appointments/create/components/place.tsx, app/user/appointments/create/page.tsx, application/usecases/appointment/DfCreateAppointmentUsecase.ts, components/header/ArrowHeader.tsx, domain/entities/Member.ts, domain/repositories/AppointmentRepository.ts, domain/repositories/PlaceVoteRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts, infrastructure/repositories/SbMemberRepository.ts, infrastructure/repositories/SbPlaceVoteRepository.ts
<br />
- 약속 생성 백엔드(Repository ~ route) 추가
- Member entity 속성(id_vote) 추가
<br />
=> [feat] 약속 생성 백엔드 및 Member entity 속성 추가

app/api/user/appointments/[id]/confirm/route.ts, app/api/user/appointments/[id]/place-vote/route.ts, app/api/user/appointments/[id]/time-vote/route.ts, app/api/user/appointments/[id]/vote-result/route.ts, app/api/user/appointments/[id]/vote/route.ts, app/user/appointments/[id]/confirm/complete/complete.module.scss, app/user/appointments/[id]/vote-place/page.tsx, application/usecases/vote/DfGetAppointmentTimeUsecase.ts.ts, application/usecases/vote/DfSubmitVoteUsecase.ts, infrastructure/repositories/SbPlaceVoteUserRepository.ts
<br />
- route에서 id값 가져오는 방법 변경
기존 방법
```ts
export async function GET( request: NextRequest) {
try {
const pathname = request.nextUrl.pathname; // ex) "/api/user/appointments/1/vote-result"
const appointmentId = parseInt(pathname.split("/").slice(-2, -1)[0]); // 마지막에서 두 번째 값 추출
}}
```
변경 후
```ts
export async function GET(
request: NextRequest,
{ params }: { params: { id: number } }
) {
try {
const { id } = await params;
const appointmentId = id;
}}
```
- 불필요한 변수 제거 isMember(DfSubmitVoteUsecase.ts), voteData(vote-place/page.tsx)
- 사용하지 않는 import 제거
=> [refactor] vote관련 페이지 리펙토링 진행

app/user/appointments/create/components/complete.tsx, context/CreateAppointmentContext.tsx
<br />
- 약속 만들기 Context에 API 연결
- 약속 만들기 userId 동적으로 가져오게 수정
<br />
=> [feat] 약속 만들기 백엔드 

app/api/user/appointments/route.ts, app/user/appointments/page.tsx, application/usecases/appointment/DfGetAppointmentCardUsecase.ts, application/usecases/appointment/dto/AppointmentCardDto.ts
<br />
- 약속 리스트 userId 동적으로 변경
<br />
=> [feat] 약속 리스트 userId 동적으로 변경

app/api/user/appointments/route.ts, app/user/appointments/components/AppointmentCard.tsx, app/user/appointments/page.tsx, application/usecases/appointment/DfGetAppointmentCardUsecase.ts, application/usecases/appointment/dto/AppointmentCardDto.ts
<br />
- 약속 리스트 페이지 로딩 및 status 속성으로 필터링
<br />
=> [feat] 약속 리스트 페이지 로딩 및 status 속성으로 필터링

app/api/user/appointments/[id]/vote-result/route.ts, app/api/user/appointments/[id]/vote/route.ts, app/layout.tsx, app/user/appointments/[id]/vote-place/page.tsx, app/user/appointments/[id]/vote-time/page.tsx, application/usecases/vote/DfGetVoteResultUsecase.ts, application/usecases/vote/DfSubmitVoteUsecase.ts, application/usecases/vote/dto/TimeVoteDto.ts, application/usecases/vote/dto/VoteDto.ts, domain/repositories/AppointmentRepository.ts, domain/repositories/MemberRepository.ts, domain/repositories/UserRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts, infrastructure/repositories/SbMemberRepository.ts, infrastructure/repositories/SbTimeVoteRepository.ts, infrastructure/repositories/SbUserRepository.ts
<br />
- 오류나기 이전상태로 revert후 머지하려 했던 내용 추가
-
<br />
-
-
=> [fix] conflict로 오류난거 수정

app/admin/appointments/appointments.module.scss, app/admin/appointments/page.tsx, app/admin/images/images.module.scss, app/admin/images/page.tsx, app/admin/layout.module.scss, app/admin/layout.tsx, app/admin/users/page.tsx, app/admin/users/users.module.scss, domain/entities/Admin.ts
<br />
1. 유저 관리 페이지
- id, email, nickname으로 검색할 수 있는 input 구현
```ts
const [searchType, setSearchType] = useState<"id" | "email" | "nickname">(
"id"
);
const [searchQuery, setSearchQuery] = useState("");
const handleSearch = async () => {
if (!searchQuery.trim()) {
fetchUsers(); // 검색어가 없으면 전체 목록 로드
return;
}
const query = new URLSearchParams({ [searchType]: searchQuery }).toString();
const res = await fetch(`/api/admin/users?${query}`);
const data = await res.json();
setUsers(data);
};
```
2. 약속 관리 페이지
- 약속 상태에 따라 필터링 할 수 있는 기능 구현
- 약속 status 값이 voting이면 "투표중"
- 약속 staus 값이 confirmed이고 confirm_time이랑 현재시간이랑 비교해서 안지났으면 "예정", 지낫으면 "완료"로 상태 정의
```ts
// ✅ 상태 필터 적용 함수
const filterAppointments = (
filter: string,
data: Appointment[] = appointments
) => {
if (filter === "all") { …
```
=> [feat] admin페이지 디자인 추가

app/user/appointments/create/components/complete.module.scss, app/user/appointments/create/components/complete.tsx, app/user/appointments/create/components/place.tsx, application/usecases/appointment/DfCreateAppointmentUsecase.ts, context/CreateAppointmentContext.tsx, domain/entities/PlaceVote.ts, domain/repositories/PlaceVoteRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts, infrastructure/repositories/SbPlaceVoteRepository.ts
<br />
- 약속 만들기 시 Member, Place_vote 테이블 생성되게 수정
- 약속 만들기 성공 페이지 디자인 수정
<br />
=> [feat] 약속 만들기 테이블 생성 로직 추가

app/admin/users/page.tsx, app/admin/users/users.module.scss, app/api/admin/users/[id]/route.ts, app/api/admin/users/route.ts, application/usecases/user/DfDeleteUserUsecase.ts, application/usecases/user/DfGetAllUsersUsecase.ts, application/usecases/user/dto/UserDeleteDto.ts, application/usecases/user/dto/UserListDto.ts, domain/repositories/UserRepository.ts, infrastructure/repositories/SbUserRepository.ts
<br />
1. 유저 리스트 불러오기 기능
```ts
const { data, error } = await supabase
.from("user")
.select("id, user_email, nickname, created_at"); // ✅ 필요한 필드만 선택
```
2. 검색기능은 client side에서 진행되도록 구현
```ts
// ✅ 검색 필터링 기능 (useEffect 사용)
useEffect(() => {
if (!searchQuery.trim()) {
setFilteredUsers(users); // 검색어가 없으면 전체 목록 표시
return;
}
// ✅ 검색어를 포함하는 유저만 필터링
const filtered = users.filter((user) =>
user[searchType].toLowerCase().includes(searchQuery.toLowerCase())
);
setFilteredUsers(filtered);
}, [searchQuery, searchType, users]);
```
3. 유저 삭제 기능 : userId 받아서 테이블에서 삭제
```ts
const { error } = await supabase.from("user").delete().eq("id", userId);
```
=> [feat] admin페이지-유저리스트불러오기, 유저삭제기능 구현

app/api/user/appointments/route.ts, app/api/user/member/route.ts, app/user/appointments/components/AppointmentList.module.scss, app/user/appointments/components/AppointmentList.tsx, app/user/appointments/page.tsx, application/usecases/appointment/DfGetAppointmentCardUsecase.ts, application/usecases/appointment/DfGetAppointmentInformationUsecase.ts, application/usecases/appointment/dto/AppointmentCardDto.ts, application/usecases/member/DfGetMemberIsVote.ts, domain/repositories/MemberRepository.ts, infrastructure/repositories/SbMemberRepository.ts
<br />
- 해당 userId를 가지고 있는 appointment 데이터가 없다면 빈 리스트로 반환하도록 하여 오류 수정
- 투표중, 확정된 약속 카드 클릭 시 리다이렉트 url 반환하는 유스케이스 추가
<br />
-
-
=> [feat] 약속 리스트 페이지 기능 오류 제어 및 Member Repository 추가

app/user/appointments/components/AppointmentList.tsx, application/usecases/member/DfGetMemberIsVote.ts
<br />
- 약속 리스트 페이지 약속 종류에 따른 리다이렉트 추가
-
<br />
-
-
=> [feat] 약속 리스트 페이지 약속 종류에 따른 리다이렉트 추가

app/user/components/UserName.tsx
<br />
- if문을 사용하여 기존 닉네임을 그대로 변경하려고 하면 변경하지 않도록 처리하였습니다.
-
<br />
-
-
=> [feat] 기존 닉네임 변경시 변경하지 않도록 처리

app/api/admin/users/[id]/route.ts, application/usecases/user/DfDeleteUserUsecase.ts
<br />
- admin페이지에서 유저삭제하는 route에서 usecase를 사용하지않고 repository를 바로 썻었는데 이걸 usecase를 사용하도록 변경
<br />
-
-
=> [feat] 어드민페이지에서 유저삭제 route에서 usecase사용하도록 변경

app/api/auth/signup/route.ts, app/api/user/delete-user/route.ts, app/user/components/DeleteAccountModalContent.tsx, app/user/page.tsx, application/usecases/user/DfDeleteUserUsecase.ts
<br />
- userId를 활용하여 해당 유저테이블에서 회원 제거를 진행합니다. 삭제 완료 후 초기화면으로 이동 합니다.
-
<br />
-
-
=> [feat] 마이페이지 회원탈퇴 기능 구현

app/user/components/DeleteAccountModalContent.tsx
<br />
- confirm을 확인하여 한번 더 확인을 받고 확인 버튼을 누르면 탈퇴가 진행됩니다.
-
<br />
-
-
=> [feat] 확인 버튼 누르기 전 한번 더 확인받기 추가

app/admin/images/images.module.scss, app/admin/images/page.tsx, app/api/admin/images/[id]/route.ts, app/api/admin/images/route.ts, application/usecases/appointmentImage/DfDeleteImageUsecase.ts, application/usecases/appointmentImage/DfGetAllImagesUsecase.ts, application/usecases/appointmentImage/dto/ImageDeleteDto.ts, application/usecases/appointmentImage/dto/ImageListDto.ts, domain/repositories/AppointmentImageRepository.ts, infrastructure/repositories/SbAppointmentImageRepository.ts
<br />
- 전체 이미지 불러오는 기능
```ts
const { data, error } = await supabase
.from("appointment_image")
.select("id, appointment_id, image_url, creater_id, created_at");
```
- 이미지 삭제 기능
```ts
// ✅ Storage + DB에서 이미지 삭제
async deleteImage(imageId: string): Promise<boolean> {
const supabase = await this.getClient();
// ✅ 1. `appointment_image` 테이블에서 해당 이미지의 `image_url` 가져오기
const { data: imageData, error: fetchError } = await supabase
.from("appointment_image")
.select("image_url")
.eq("id", imageId)
.single();
if (fetchError || !imageData) {
console.error("❌ 이미지 정보를 찾을 수 없음:", fetchError?.message);
return false;
}
const imageUrl = imageData.image_url;
// ✅ 2. Storage에서 이미지 삭제 (파일 경로 추출)
const filePath = imageUrl.replace(
"https://yswjnlalguzoxdcmydxr.supabase.co/storage/v1/object/public/images/", …
```
=> [feat] admin-이미지 관리기능 추가

app/api/user/appointments/[id]/confirm/route.ts, app/user/appointments/[id]/confirm/page.tsx, app/user/appointments/[id]/vote-result/page.tsx, app/user/appointments/[id]/vote-result/voteResult.module.scss, app/user/appointments/[id]/vote-time/page.tsx
<br />
1. 투표 관련 페이지에 로그인 확인 로직 추가
- getUserIdClient() 함수 사용하여 쿠키케 userId 있는지 확인하여 로그인상태인지 확인
2. 방장일 경우 투표결과 페이지에서 무조건 확정페이지로 가는 버튼바께 없었음 -> 홈으로 가기 버튼추가
3. 약속확정에서 장소url이 없는경우 오류 해결
<br />
-
-
=> [feat] 투표관련페이지 오류수정 및 로그인확인 로직 추가

app/user/appointments/create/components/place.tsx, app/user/appointments/create/components/time.tsx, context/CreateAppointmentContext.tsx, domain/entities/Appointment.ts, utils/dateUtils/dateUtils.ts
<br />
- appointment의 result 속성 제외
- 한국 날짜 -> ISO 날짜로 바꾸는 중 일자가 바뀌는 문제 해결 (유틸 함수 만듦)
- 약속 생성 시 오류 뜨면 완성 페이지로 안 넘어가게 제어 추가
<br />
=> [fix] 약속 만들기 오류 해결

app/user/appointments/create/components/time.tsx
<br />
- 약속 만들기 시간 선택 시 유효성 검사 추가
-
<br />
-
-
=> [feat] 약속 만들기 시간 선택 시 유효성 검사 추가

app/api/user/user-appointments/route.ts, app/user/components/MyCalendar.tsx, application/usecases/appointment/DfGetUserAppointmentsUsecase.ts, application/usecases/appointment/dto/UserAppointmentListDto.ts
<br />
- 해당 userId를 쿠키에서 get하여 유즈케이스를 활용해 멤버, 방장 리스트를 가지고와 배열로 받고, 해당 약속 리스트를 FullCalendar 라이브러리에 연동하였습니다. 
-
<br />
-
-
=> [feat] 마이페이지 달력 연동하기

components/header/Header.tsx
<br />
- 헤더 동적 닉네임으로 수정
<br />
=> [feat] 헤더 동적 닉네임으로 수정

app/user/appointments/[id]/confirm/complete/page.tsx, app/user/appointments/[id]/confirm/confirm.module.scss, app/user/appointments/[id]/vote-place/layout.tsx, app/user/appointments/[id]/vote-place/page.tsx, app/user/appointments/[id]/vote-place/votePlace.module.scss, app/user/appointments/[id]/vote-result/components/PlaceResult.module.scss, app/user/appointments/[id]/vote-result/components/TimeResult.module.scss, app/user/appointments/[id]/vote-result/layout.tsx, app/user/appointments/[id]/vote-result/page.tsx, app/user/appointments/[id]/vote-result/voteResult.module.scss, app/user/appointments/[id]/vote-time/layout.tsx, app/user/appointments/[id]/vote-time/page.tsx, app/user/appointments/[id]/vote-time/voteTime.module.scss, utils/copy/copyUtils.ts
<br />
1. 모바일환경드레그개선
```ts
// ✅ 터치 이벤트
const handleTouchStart = (
event: React.TouchEvent,
row: number,
col: number
) => {
isDragging.current = true;
dragValue.current = !gridSelected[row][col];
// ✅ 기존 timeout이 있다면 클리어
if (touchTimeout.current) {
clearTimeout(touchTimeout.current);
}
// ✅ 터치 후 100ms 내에 `touchmove`가 발생하지 않으면 단일 선택 적용
touchTimeout.current = setTimeout(() => {
if (isDragging.current) {
toggleCell(row, col);
lastTouchedCell.current = { row, col };
}
}, 100);
};
// ✅ 터치 이동 시 여러 셀을 선택하도록 개선
const handleTouchMove = (event: React.TouchEvent) => {
if (!isDragging.current) return;
// ✅ 단순한 터치라면 `setTimeout` 해제 (즉, 드래그로 간주)
if (touchTimeout.current) {
clearTimeout(touchTimeout.current);
touchTimeout.current = null;
}
const touch = event.touches[0];
const target = …
```
=> [feat] 시간투표-모바일환경드레그개선,헤더 레이아웃으로적용, 모바일환경 복사기능 개선

app/(anon)/login/components/LoginForm.tsx, app/(anon)/login/components/LogoWithTitle.tsx, app/user/components/MyCalendar.tsx, app/user/components/UserImage.tsx, app/user/components/UserImageModalContent.tsx, app/user/components/user-skeleton/CalendarSkeleton.module.scss, app/user/components/user-skeleton/CalendarSkeleton.tsx, app/user/components/user-skeleton/EmojiSkeleton.module.scss, app/user/components/user-skeleton/EmojiSkeleton.tsx, app/user/components/user-skeleton/EmojisSkeleton.module.scss, app/user/components/user-skeleton/EmojisSkeleton.tsx, components/modal/Modal.tsx
<br />
- 각각 컴포넌트에 loading 상태를 추가하여, loading 상태에 따른 스켈레톤 UI를 적용하였습니다.
- 모달 컴포넌트에 로고 Image `.webp` 을 사용하여 `svg`로 변경하였습니다.
-
<br />
-
-
=> [feat] 마이페이지 각 컴포넌트에 스켈레톤 UI 적용

components/header/components/DropdownMenu.module.scss
<br />
- 헤더 드롭 다운 위치 수정
<br />
=> [style] 헤더 드롭 다운 위치 수정

app/admin/appointments/appointments.module.scss, app/admin/images/images.module.scss, app/admin/layout.module.scss, app/admin/users/users.module.scss, app/user/appointments/[id]/confirm/confirm.module.scss, app/user/appointments/[id]/vote-place/votePlace.module.scss, app/user/appointments/[id]/vote-result/components/PlaceResult.module.scss, app/user/appointments/[id]/vote-result/voteResult.module.scss
<br />
- css속성 glabalCSS속성으로 변경 (font-size 및 색상)
<br />
-
-
=> [sytle] css속성 glabalCSS속성으로 변경

app/(anon)/page.tsx, app/admin/appointments/page.tsx, app/admin/images/page.tsx, app/admin/users/page.tsx, application/usecases/auth/DfSignUpUseCase.ts, application/usecases/auth/DfSocialLoginUseCase.ts, domain/entities/User.ts, domain/repositories/UserRepository.ts, infrastructure/repositories/SbUserRepository.ts
<br />
- 현재 로그인한 userId가 admin userId와 일치 하지 않을 시 에러메시지를 보여주며 user/appointments 페이지로 이동합니다.
```tsx
const [errorMessage, setErrorMessage] = useState<string>("");
const [userId, setUserId] = useState<string | null>(null);
const router = useRouter();
useEffect(() => {
const checkUser = async () => {
const currentUserId = await getUserIdClient();
setUserId(currentUserId);
if (currentUserId !== ADMIN_USER_ID) {
setErrorMessage(
"이 페이지는 관리자 전용입니다. 권한이 없는 사용자로는 접근할 수 없습니다."
);
setTimeout(() => {
router.push("/user/appointments");
}, 2000);
}
};
checkUser();
}, [router]);
```
-
<br />
-
-
=> [feat] admin 페이지 권한 체크

app/admin/images/page.tsx, domain/entities/User.ts
<br />
- 유저 타입으로 인한 오류 해결
-
<br />
-
-
=> [fix] user타입 변경

app/api/user/update-emoji/route.ts, app/user/components/UserImageModalContent.tsx
<br />
- 이모지 업데이트는 부분 수정이기 때문에 POST보단 PATCH가 맞기 때문에 PATCH로 수정하였습니다.
-
<br />
-
-
=> [refactor] fetch요청 POST -> PATCH로 변경

app/api/user/appointments/[id]/gallery/route.ts, app/user/appointments/[id]/gallery/page.tsx, application/usecases/appointmentImage/DfCreateImageUsecase.ts, application/usecases/appointmentImage/dto/ImageUploadDto.ts, domain/repositories/AppointmentImageRepository.ts, infrastructure/repositories/SbAppointmentImageRepository.ts
<br />
- 사진 업로드 (POST) 구현 (닉네임 제외)
-
<br />
=> [feat] 사진 업로드 (POST) 구현 (닉네임 제외)

app/user/components/UserAppointmentCount.tsx
<br />
`기존 방법`
```tsx
const votingCount =
appointments?.filter((appointment) => {
const { status } = getEventsStatus(appointment);
return status === "voting";
}).length ?? 0;
const scheduledCount =
appointments?.filter((appointment) => {
const { status } = getEventsStatus(appointment);
return status === "scheduled";
}).length ?? 0;
const confirmedCount =
appointments?.filter((appointment) => {
const { status } = getEventsStatus(appointment);
return status === "confirmed";
}).length ?? 0;
```
`수정 코드`
```tsx
const getAppointmentCount = (status: string) => {
return (
appointments?.filter((appointment) => {
const { status: appointmentStatus } = getEventsStatus(appointment);
return appointmentStatus === status;
}).length ?? 0
);
};
const votingCount = getAppointmentCount("voting");
const …
```
=> [refactor] 중복되는 함수를 getAppointmentCount 함수로 분리

app/api/user/check-appointment-entry/route.ts, app/user/appointments/Appointments.module.scss, app/user/appointments/components/EntryAppointmentModal.module.scss, app/user/appointments/components/EntryAppointmentModal.tsx, app/user/appointments/hooks/useAppointments.ts, app/user/appointments/hooks/useEnrtyAppointmentModal.ts, app/user/appointments/page.tsx
<br />
- 약속 리스트 페이지 코드 리팩토링
- 커스텀 훅으로 비즈니스 로직 분리
- 모달 파일 분리 및 커스텀 훅 분리
- 각 함수 단일 책임을 갖게 분리
- 방 참여하기 : 이미 참여한 사람, 일치 하는 방이 없을 시 오류 제어
<br />
-
-
=> [refactor] 약속 리스트 페이지 코드 리팩토링

app/api/user/update-nickname/route.ts, app/user/components/UserName.tsx
<br />
- 닉네임이 supabase user 테이블에서 해당 닉네임이 중복일 경우 닉네임 중복 메시지를 보여줍니다.
-
<br />
-
-
=> [fix] 닉네임 중복 에러 처리

app/(anon)/login/components/LoginForm.tsx, app/(anon)/login/hooks/useLogin.ts
<br />
- 기존 Login 컴포넌트에서 모든 처리를 하였지만 비즈니스 로직을 따로 분리하여 헤드리스 컴포넌트를 구현하였습니다.
-
<br />
-
-
=> [refactor] useLogin으로 비즈니스 로직 분리

app/api/user/appointments/[id]/vote/route.ts, app/user/appointments/[id]/(member)/confirm/confirm.module.scss, app/user/appointments/[id]/(member)/confirm/page.tsx, app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.module.scss, app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.tsx, app/user/appointments/[id]/(member)/vote-result/components/TimeResult.module.scss, app/user/appointments/[id]/(member)/vote-result/page.tsx, app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss, app/user/appointments/[id]/(member)/vote-time/voteTime.module.scss
<br />
-시간투표 그리드 위치조정, 장소투표 카운트추가
-
<br />
-
-
=> [style] 시간투표 그리드 위치조정, 장소투표 카운트추가

app/(anon)/signup/components/AuthForm.tsx, app/(anon)/signup/hooks/useCheckNickname.ts, app/(anon)/signup/hooks/useForm.ts, app/(anon)/signup/hooks/useSubmitSignup.ts
<br />
- 회원가입 form에서 비즈니스 로직을 분리하였습니다.
- 닉네임 중복 체크 함수, 회원가입 함수를 따로 분리하여 사용했습니다.
-
<br />
-
-
=> [refactor] 회원가입 비즈니스 로직 분리

app/api/user/appointments/[id]/information/member/route.ts, app/api/user/appointments/[id]/information/route.ts, app/user/appointments/[id]/(member)/information/page.tsx
<br />
1. 특정약속에서 멤버삭제하는기능 추가
```ts
async deleteMember(userId: string, appointmentId: number): Promise<void> {
const supabase = await createClient();
const { error } = await supabase
.from("member")
.delete()
.eq("user_id", userId)
.eq("appointment_id", appointmentId);
if (error) {
console.error(`member 삭제 실패:`, error);
throw new Error(`Failed to delete member: ${error.message}`);
}
}
``
<br />
-
-
=> [feat] 특정약속에서 멤버삭제하는기능 추가

app/user/appointments/create/hooks/useCreateComplete.ts, app/user/appointments/create/hooks/useCreateInformaion.ts, context/CreateAppointmentContext.tsx
<br />
- createAppointment context API 메모제이션 추가
- 약속 만들기 비밀번호 작성 시 lowerCase로 작성 되는거 수정
- 링크 복사 유틸 함수 사용 시 버튼 활성화가 2초 밖에 안 되는 문제 해결 -> 버튼 활성화 지속되게 수정
<br />
-
-
=> [refactor] 약속 만들기 페이지 리팩토링

app/admin/appointments/page.tsx, app/admin/images/page.tsx, app/admin/layout.tsx, app/admin/users/page.tsx, app/api/admin/appointments/[id]/route.ts, app/api/admin/appointments/route.ts, app/api/admin/images/[id]/route.ts, app/api/admin/images/route.ts, app/api/admin/users/[id]/route.ts, app/api/admin/users/route.ts, app/api/user/appointments/[id]/confirm/route.ts, app/api/user/appointments/[id]/place-vote/route.ts, app/api/user/appointments/[id]/route.ts, app/api/user/appointments/[id]/time-vote/route.ts, app/api/user/appointments/[id]/vote-result/route.ts, app/api/user/appointments/[id]/vote/route.ts, app/user/appointments/[id]/(member)/confirm/page.tsx, app/user/appointments/[id]/(member)/layout.tsx
<br />
-모든 함수 arrow function으로 교체
-
<br />
-
-
=> [feat] arrow function으로 교체

app/(anon)/page.module.scss
<br />
- 버튼 크기를 크게 키웠습니다. 해당 페이지 container에 padding을 주었습니다. 화면 크기가 줄어들어도 padding값으로 꽉차지 않고 여유롭게 수정하였습니다.
-
<br />
-
-
=> [style] 버튼 크기 수정 및 컨테이너 수정

app/user/components/AppointmentCount.module.scss, app/user/components/UserAppointmentCount.module.scss
<br />
- `mediaquery` 를 사용하여 화면 크기에 따라 스타일을 수정하였습니다.
```scss
// AppointmentCount.module.scss
@media (max-width: 768px) {
width: 60px;
height: 60px;
}
@media (max-width: 375px) {
width: 50px;
height: 50px;
span:nth-child(2) {
font-size: var(--font-size-xxs);
font-family: var(--font-main);
}
}
```
```scss
// UserAppointmentCount.module.scss
@media (max-width: 768px) {
top: 30%;
left: 42%;
}
@media (max-width: 375px) {
top: 25%;
left: 47%;
gap: 10px;
}
```
<br />
-
-
=> [style] mediaquery 추가

app/admin/hooks/useAdminCheck.ts
<br />
```tsx
// useAdminCheck.ts
if (!currentUserId) {
alert("로그인되지 않았습니다. 로그인 페이지로 이동합니다.");
router.push("/login");
return;
}
```
- 로그인 하지 않은 유저가 url로 직접 들어와도 로그인 하지 않은 유저라면 로그인 페이지로 리다이렉트 합니다.
<br />
-
-
=> [feat] 관리자 페이지 로그인 되지 않은 유저 에러처리

app/(anon)/login/components/LoginForm.tsx, app/(anon)/page.tsx, app/(anon)/signup/page.tsx
<br />
- import하고 사용하지 않은 모듈을 제거하였습니다.
-
<br />
-
-
=> [chore] 필요하지 않은 모듈 제거

app/api/admin/appointments/[id]/route.ts, app/api/admin/images/[id]/route.ts, app/api/user/appointments/[id]/confirm/route.ts, app/api/user/appointments/[id]/place-vote/route.ts, app/api/user/appointments/[id]/route.ts, app/api/user/appointments/[id]/time-vote/route.ts, app/api/user/appointments/[id]/vote-result/route.ts
<br />
- route.ts에서 id값 못받아오는 오류 수정 -> `  { params }: { params: { id: string } }
` 이렇게 받아오기 위해선 아래와 같이 request: NextResponse도 써줘야 한다.
```ts
export const DELETE = async (
request: NextResponse,
{ params }: { params: { id: string } }
) => {
```
-
<br />
-
-
=> [fix] route.ts에서 id값 못받아오는 오류 수정

app/api/user/appointments/[id]/confirm/route.ts, app/api/user/appointments/[id]/place-vote/route.ts, app/api/user/appointments/[id]/vote-result/route.ts, app/api/user/appointments/[id]/vote/route.ts, app/user/appointments/[id]/(member)/confirm/page.tsx, app/user/appointments/[id]/(member)/vote-place/page.tsx, app/user/appointments/[id]/(member)/vote-result/page.tsx
- <br />
- console.error -> console.log로 변경
<br />
=> [chore] console.error -> console.log로 변경

app/(anon)/login/components/KakaoLogin.tsx, app/(anon)/page.tsx, app/(anon)/signup/components/EmailInputField.module.scss, app/api/auth/callback/route.ts, app/api/auth/check-nickname/route.ts, app/api/auth/logout/route.ts, app/api/auth/signup/route.ts, app/api/user/[userId]/route.ts, context/UserContext.tsx
- <br />
- 사용하지 않는 스타일 주석 삭제하였습니다..
- `console.error` -> `console.log`로 변경하였습니다.
<br />
👋🏻
=> [fix] error message 변경

app/user/appointments/[id]/(member)/gallery/page.tsx
<br />
- import 오타 수정하였습니다. 
-
<br />
-
-
=> [fix] import 오타 수정

app/user/components/MyCalendar.tsx
<br />
- onAppointmentsFetch 함수를 의존성 배열에 추가하였습니다.
```tsx
useEffect(() => {
const appointmentsListFetch = async () => {
setIsLoading(true);
const response = await fetch("/api/user/user-appointments");
const appointments = await response.json();
const transformedEvents = appointments.map((event: Event) => {
const { status, color } = getEventsStatus(event);
return {
...event,
status,
color,
};
});
setEvents(transformedEvents);
onAppointmentsFetch(transformedEvents);
setIsLoading(false);
};
appointmentsListFetch();
}, [onAppointmentsFetch]);
```
-
<br />
-
-
=> [fix] 의존성 배열에 onAppointmentsFetch 추가

app/api/user/appointments/create/route.ts, app/user/appointments/[id]/entry/hooks/useEntry.ts, app/user/appointments/components/AppointmentCard.module.scss, app/user/appointments/create/components/createPlace.module.scss, app/user/appointments/hooks/useAppointments.ts
<br />
- 배포중 경고 오류 수정
- 약속 만들기 라우터 오류 제어
- useEffect 의존성 경고 해결
- 스타일 경고 수정
<br />
-
-
=> [fix] 배포중 경고 오류 수정

app/api/admin/appointments/[id]/route.ts, app/api/admin/images/[id]/route.ts, app/api/user/appointments/[id]/confirm/route.ts, app/api/user/appointments/[id]/place-vote/route.ts, app/api/user/appointments/[id]/route.ts, app/api/user/appointments/[id]/time-vote/route.ts, app/api/user/appointments/[id]/vote-result/route.ts, app/api/user/appointments/[id]/vote/route.ts, app/user/appointments/[id]/(member)/confirm/confirm.module.scss, app/user/appointments/[id]/(member)/vote-result/components/PlaceResult.module.scss, application/usecases/appointment/DfDeleteAppointmentUsecase.ts, application/usecases/appointmentImage/DfDeleteImageUsecase.ts, domain/repositories/AppointmentImageRepository.ts, domain/repositories/AppointmentRepository.ts, infrastructure/repositories/SbAppointmentImageRepository.ts, infrastructure/repositories/SbAppointmentRepository.ts
<br />
- autoprefixer 관련리팩토링
```ts
// 기존 코드
justify-content: start; 
justify-content: end; 
// 수정된 코드
justify-content: flex-start; 
justify-content: flex-end; 
```
-[id] 동적 경로에서 params 처리 문제관련 리팩토링
- route.ts에서 { params }: { params: { id: number } } 이 방식이 Next.js 13 이상에서 올바르지 않을 수 있음.
- Next.js에서는 id가 string으로 들어오므로 숫자로 변환해야 함.
<br />
-
-
=> [refactor] autoprefixer 관련리팩토링,[id] 동적 경로에서 params 처리 문제관련 리팩토링

app/api/admin/appointments/[id]/route.ts, app/api/admin/images/[id]/route.ts, app/api/user/appointments/[id]/confirm/route.ts, app/api/user/appointments/[id]/place-vote/route.ts, app/api/user/appointments/[id]/route.ts, app/api/user/appointments/[id]/time-vote/route.ts, app/api/user/appointments/[id]/vote-result/route.ts
<br />
-NextResponse-> NextRequest
-
<br />
-
-
=> [fix] NextResponse-> NextRequest

app/api/user/appointments/create/route.ts, app/api/user/appointments/route.ts, app/user/appointments/hooks/useAppointments.ts
- [] 디자인 작업
<br />
- route NextRequest로 변경
<br />
=> [feat] route NextRequest로 변경

app/api/admin/appointments/[id]/route.ts
=> [fix] 배포 중 오류 수정

app/api/admin/appointments/[id]/route.ts
Reverts FRONT-END-BOOTCAMP-PLUS-3/moongchija#202
=> Revert "[fix] 배포 중 오류 수정"

app/api/admin/appointments/[id]/route.ts
=> [fix] route 빌드 오류 수정

app/admin/appointments/page.tsx, app/api/admin/appointments/[id]/route.ts
=> [fix] 빌드오류 수정

app/api/user/appointments/[id]/route.ts, infrastructure/repositories/SbMemberRepository.ts
- <br />
- 멤버인지 확인하는 route 오류 수정
<br />
👋🏻
=> [fix] 멤버인지 확인하는 route 오류 수정

components/button/Button.module.scss
- <br />
- 버튼 border-radius 수정
<br />
👋🏻
=> [style] 버튼 border-radius 수정

app/user/components/DeleteAccountModalContent.tsx, components/modal/Modal.module.scss
- <br />
```scss
.modalContainer{
width: 480px;
.modalWrapper {
width: 400px;
}
``` 
기존 코드
```scss
.modalContainer{
width: 100%;
.modalWrapper {
max-width: 400px;
width: 100%;
@media (max-width: 400px) {
max-width: 350px;
width: 100%;
}
}
``` 
화면 너비에 따른 반응형을 추가하였습니다.
<br />
👋🏻
=> [style] ui/modal

app/user/appointments/[id]/(member)/vote-result/components/TimeResult.module.scss, app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss, app/user/appointments/[id]/(member)/vote-time/voteTime.module.scss
- <br />
- 반응형을 위해 미디어쿼리 추가
```scss
.weekDay {
width: 45px;
font-size: var(--font-size-sm);
text-align: center;
margin-right: 5px;
color: var(--grey-3-color);
@media (max-width: 390px) {
width: 40px;
margin-right: 4.5px;
}
@media (max-width: 375px) {
width: 37px;
margin-right: 5px;
}
}
.day {
width: 45px;
font-size: var(--font-size-md);
text-align: center;
margin-right: 5px;
margin-bottom: 1vh;
@media (max-width: 390px) {
width: 40px;
margin-right: 4.5px;
}
@media (max-width: 375px) {
width: 37px;
margin-right: 5px;
}
}
```
<br />
👋🏻
=> [style] 반응형을 위해 미디어쿼리 추가

app/user/components/AppointmentCount.module.scss, app/user/components/MyCalendar.scss, app/user/components/UserImage.module.scss, app/user/components/UserImage.tsx, app/user/components/UserName.module.scss, app/user/components/UserName.tsx, app/user/mypage.module.scss
- <br />
- 기존 이모지 닉네임 배치 row에서 column으로 변경하였습니다.
- 약속 개수 디자인도 기본 원형에서 사각형으로 변경하였습니다.
- 닉네임 수정 클릭 시 취소 버튼 대신 esc, click을 하면 취소 되게 변경하였습니다.
<br />
👋🏻
=> [style] 마이페이지 UI 수정

app/globals.css, app/user/components/AppointmentCount.module.scss
- <br />
- 약속 개수 컴포넌트에 `box-shadow` 를 추가하였습니다.
-
<br />
=> [style] 마이 페이지 약속 개수 컴포넌트 스타일 수정

app/admin/appointments/appointments.module.scss
- <br />
- admin페이지 약속상태 컬러 변경
=> [style] admin페이지 약속상태 컬러 변경

app/user/components/AppointmentCount.module.scss, app/user/components/MyCalendar.tsx, app/user/components/UserAppointmentCount.module.scss, app/user/components/UserAppointmentCount.tsx, app/user/page.tsx
- <br />
`약속 전체 개수 카운팅`
```tsx
const totalCount = appointments?.length ?? 0;
```
`약속 개수 버튼을 클릭하면 해당 상태를 부모 컴포넌트에게 전달`
```tsx
<button
key={index}
onClick={() => {
onStatusChange(
item.text === "투표중"
? "voting"
: item.text === "예정"
? "scheduled"
: item.text === "종료"
? "confirmed"
: null
);
}}
className={styles.statusButton}
>
```
```tsx
// 마이페이지 컴포넌트
const [selectedStatus, setSelectedStatus] = useState<string | null>(null);
<UserAppointmentCount appointments={appointments} onStatusChange={setSelectedStatus} />
<MyCalendar onAppointmentsFetch={setAppointments} selectedStatus={selectedStatus} />
```
`필터링 기능`
```tsx
// MyCalendar 컴포넌드
const filteredEvents = selectedStatus
? events.filter((event) => event.status === selectedStatus)
: events;
```
👋🏻
=> [feat] 약속 필터링 기능 추가

app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss, next.config.mjs
=> [fix] pwa설정중 webpack관련 오류 수정, 투표결과페이지 미디어쿼리 설정

app/api/user/appointments/[id]/information/member/route.ts, app/user/appointments/[id]/(member)/components/information/Participants/Participants.tsx, app/user/appointments/[id]/(member)/information/page.tsx
- <br />
- 약속나가기 오류수정 -> route경로 문제였음
-
<br />
👋🏻
=> [fix] 약속나가기 오류

infrastructure/repositories/SbAuthRepository.ts
- <br />
- 로그인 시 비밀번호를 잘 못 입력했을 시 출력되는 에러메시지를 수정하였습니다.
-
<br />
👋🏻
=> [fix] 로그인 실패 시 에러메시지 수정

app/(anon)/signup/signup.module.scss
- <br />
- 기존 padding이 없어서 화면이 작으면 꽉차는 상태였는데, padding 을 추가하였습니다.
-
<br />
👋🏻
=> [style] 회원가입 페이지 padding 추가

app/user/appointments/components/AppointmentCard.module.scss, app/user/appointments/components/AppointmentCard.tsx, app/user/appointments/components/AppointmentList.module.scss, app/user/appointments/components/AppointmentList.tsx, app/user/appointments/hooks/useAppointments.ts, app/user/appointments/page.tsx, application/usecases/appointment/DfGetAppointmentCardUsecase.ts, application/usecases/appointment/dto/AppointmentCardDto.ts
- <br />
- 약속 만들기 페이지 방 나가기, 삭제 기능 추가
- 페이지 margin 수정
<br />
👋🏻
=> [feat] 약속 만들기 페이지 방 나가기, 삭제 기능 추가

application/usecases/vote/DfSubmitVoteUsecase.ts, domain/entities/TimeVoteUser.ts, domain/repositories/MemberRepository.ts, domain/repositories/PlaceVoteUserRepository.ts, domain/repositories/TimeVoteUserRepository.ts, infrastructure/repositories/SbMemberRepository.ts, infrastructure/repositories/SbPlaceVoteUserRepository.ts, infrastructure/repositories/SbTimeVoteUserRepository.ts
- <br />
- 멤버삭제시 투표기록 남아있던 오류 수정
- 멤버 테이블에 member_id를 추가 하고 fk로 설정후 casecade로 설정하여 멤버가 삭제되면 투표내용도 사라지게 설정
<br />
👋🏻
=> [feat] 멤버삭제시 투표기록 남아있던 오류 수정

app/user/appointments/create/components/createComplete.tsx
- <br />
- 약속 생성 완료 페이지 글자 수정
-
<br />
👋🏻
=> [style] 약속 생성 완료 페이지 글자 수정

app/user/appointments/[id]/(member)/vote-result/voteResult.module.scss
- <br />
- 투표결과페이지 버튼위치 수정
<br />
👋🏻
=> [style] 투표결과페이지 버튼위치 수정

app/user/appointments/create/hooks/useCreateTime.ts
- <br />
- 약속 만들기 달력 선택 7일까지만 선택되도록 수정
-
<br />
👋🏻
=> [fix] 약속 만들기 달력 선택 7일까지만 선택되도록 수정

app/(anon)/login/hooks/useLogin.ts, app/api/auth/login/route.ts, context/UserContext.tsx
- <br />
- 기존 약속 링크를 받고 입장하면 로그인이 필요합니다. 안내문을 받고 로그인을 하면 메인 페이지로 이동하였습니다.
- 편의성을 위해 해당 화면에서 로그인을 이동하면 해당 페이지를 `localStorage` 에 저장하며, 로그인을 완료하면 `localStorage` 에 pathname이 있다면 해당 url로 리다이렉트 합니다. 
- 초기화면에서 로그인을 한다면 메인페이지로 이동합니다.
<br />
👋🏻
=> [feat] 약속 링크 받고 로그인 후 약속 퀴즈 방으로 이동하기
